/* eslint-disable max-lines */

const EXERCISE_MOVEMENT_CATALOG = [
  {
    slug: 'flat-press',
    name: 'Flat Press',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Bench Press', 'Flat Bench Press', 'Dumbbell Flat Press'],
    variants: [
      {
        source_name: 'Bench Press',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Chest',
      },
      {
        source_name: 'Dumbbell Flat Press',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Chest',
      },
      {
        source_name: 'Smith Flat Press',
        variant_label: 'Smith',
        variant_kind: 'support',
        sort_order: 3,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'incline-press',
    name: 'Incline Press',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Incline Dumbbell Press', 'Incline Bench Press'],
    variants: [
      {
        source_name: 'Incline Dumbbell Press',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Chest',
      },
      {
        source_name: 'Incline Chest Press',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'decline-press',
    name: 'Decline Press',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Decline Bench Press', 'Decline Chest Press', 'Decline Dumbbell Press'],
    variants: [
      {
        source_name: 'Decline Bench Press',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Chest',
      },
      {
        source_name: 'Decline Dumbbell Press',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'chest-fly',
    name: 'Chest Fly',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'fly',
    aliases: ['Cable Chest Fly', 'Pec Deck Fly'],
    variants: [
      {
        source_name: 'Chest Fly',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Chest',
      },
      {
        source_name: 'Pec Deck Fly',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'incline-fly',
    name: 'Incline Fly',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'fly',
    aliases: ['Incline Cable Fly'],
    variants: [
      {
        source_name: 'Incline Cable Fly',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'push-up',
    name: 'Push-up',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Pushup'],
    variants: [
      {
        source_name: 'Push-up',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'chest-dip',
    name: 'Chest Dip',
    category: 'strength',
    primary_muscle_group: 'Chest',
    primary_day: 'push',
    movement_family: 'dip',
    aliases: ['Dips (Chest Bias)', 'Chest Dips'],
    variants: [
      {
        source_name: 'Dips (Chest Bias)',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Chest',
      },
    ],
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'pulldown',
    aliases: ['Pulldown'],
    variants: [
      {
        source_name: 'Lat Pulldown',
        variant_label: 'Standard Cable',
        variant_kind: 'grip',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Cable',
        primary_muscle_group: 'Back',
      },
      {
        source_name: 'Wide Grip Lat Pulldown',
        variant_label: 'Wide Grip Cable',
        variant_kind: 'grip',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Cable',
        primary_muscle_group: 'Back',
      },
      {
        source_name: 'Close Grip Lat Pulldown',
        variant_label: 'Close Grip Cable',
        variant_kind: 'grip',
        sort_order: 3,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Cable',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'seated-row',
    name: 'Seated Row',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'row',
    aliases: ['Seated Cable Row'],
    variants: [
      {
        source_name: 'Seated Cable Row',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Cable',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'single-arm-row',
    name: 'Single-Arm Row',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'row',
    aliases: ['Single Arm Dumbbell Row', 'One Arm Row'],
    variants: [
      {
        source_name: 'Single Arm Dumbbell Row',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'chest-supported-row',
    name: 'Chest-Supported Row',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'row',
    aliases: ['Chest Supported Row'],
    variants: [
      {
        source_name: 'Chest Supported Row',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'bent-over-row',
    name: 'Bent-Over Row',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'row',
    aliases: ['Bent Over Barbell Row', 'Barbell Row'],
    variants: [
      {
        source_name: 'Bent Over Barbell Row',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'pull-up',
    name: 'Pull-up',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'pull-up',
    aliases: ['Pullup'],
    variants: [
      {
        source_name: 'Pull-up',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Back',
      },
      {
        source_name: 'Assisted Pull-up',
        variant_label: 'Assisted Machine',
        variant_kind: 'support',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'chin-up',
    name: 'Chin-up',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'pull-up',
    aliases: ['Chinup'],
    variants: [
      {
        source_name: 'Chin-up',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Back',
      },
      {
        source_name: 'Assisted Chin-up',
        variant_label: 'Assisted Machine',
        variant_kind: 'support',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'pull',
    aliases: ['Cable Face Pull'],
    variants: [
      {
        source_name: 'Face Pull',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'shrug',
    name: 'Shrug',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'shrug',
    aliases: ['Dumbbell Shrug'],
    variants: [
      {
        source_name: 'Shrug',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'back-extension',
    name: 'Back Extension',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'extension',
    aliases: ['Hyperextension'],
    variants: [
      {
        source_name: 'Back Extension',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 't-bar-row',
    name: 'T-Bar Row',
    category: 'strength',
    primary_muscle_group: 'Back',
    primary_day: 'pull',
    movement_family: 'row',
    aliases: ['T Bar Row'],
    variants: [
      {
        source_name: 'T-Bar Row',
        variant_label: 'T-Bar',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Back',
      },
    ],
  },
  {
    slug: 'squat',
    name: 'Squat',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'squat',
    aliases: ['Barbell Squat', 'Front Squat', 'Goblet Squat', 'Goblet Sumo Squat', 'Dumbbell Sumo Squat'],
    variants: [
      {
        source_name: 'Back Squat',
        variant_label: 'Back Barbell',
        variant_kind: 'position',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Front Squat',
        variant_label: 'Front Barbell',
        variant_kind: 'position',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Goblet Squat',
        variant_label: 'Goblet Dumbbell',
        variant_kind: 'load_style',
        sort_order: 3,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Goblet Sumo Squat',
        variant_label: 'Goblet Sumo Dumbbell',
        variant_kind: 'position',
        sort_order: 4,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Smith Squat',
        variant_label: 'Smith',
        variant_kind: 'support',
        sort_order: 5,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'press',
    aliases: ['Machine Leg Press'],
    variants: [
      {
        source_name: 'Leg Press',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'hack-squat',
    name: 'Hack Squat',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'squat',
    aliases: ['Machine Hack Squat'],
    variants: [
      {
        source_name: 'Hack Squat',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'deadlift',
    name: 'Deadlift',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'hinge',
    aliases: ['Conventional Deadlift'],
    variants: [
      {
        source_name: 'Deadlift',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'hinge',
    aliases: ['RDL'],
    variants: [
      {
        source_name: 'Romanian Deadlift',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'thrust',
    aliases: ['Barbell Hip Thrust'],
    variants: [
      {
        source_name: 'Hip Thrust',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Glute Drive',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'hip-abduction',
    name: 'Hip Abduction',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'abduction',
    aliases: ['Outer Thigh Abduction'],
    variants: [
      {
        source_name: 'Hip Abduction',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'hip-adduction',
    name: 'Hip Adduction',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'adduction',
    aliases: ['Inner Thigh Adduction'],
    variants: [
      {
        source_name: 'Hip Adduction',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'lunge',
    aliases: ['Dumbbell Walking Lunge'],
    variants: [
      {
        source_name: 'Walking Lunge',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'split squat',
    aliases: ['Split Squat'],
    variants: [
      {
        source_name: 'Bulgarian Split Squat',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'extension',
    aliases: ['Machine Leg Extension'],
    variants: [
      {
        source_name: 'Leg Extension',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'leg-curl',
    name: 'Leg Curl',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'curl',
    aliases: ['Hamstring Curl'],
    variants: [
      {
        source_name: 'Lying Leg Curl',
        variant_label: 'Lying Machine',
        variant_kind: 'position',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Seated Leg Curl',
        variant_label: 'Seated Machine',
        variant_kind: 'position',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'calf-raise',
    name: 'Calf Raise',
    category: 'strength',
    primary_muscle_group: 'Legs',
    primary_day: 'legs',
    movement_family: 'raise',
    aliases: ['Standing Calf Raise', 'Seated Calf Raise'],
    variants: [
      {
        source_name: 'Standing Calf Raise',
        variant_label: 'Standing Machine',
        variant_kind: 'position',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
      {
        source_name: 'Seated Calf Raise',
        variant_label: 'Seated Machine',
        variant_kind: 'position',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Legs',
      },
    ],
  },
  {
    slug: 'overhead-press',
    name: 'Overhead Press',
    category: 'strength',
    primary_muscle_group: 'Shoulders',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Shoulder Press', 'Military Press', 'Arnold Press'],
    variants: [
      {
        source_name: 'Shoulder Press',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Overhead Press',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Arnold Press',
        variant_label: 'Arnold Dumbbell',
        variant_kind: 'load_style',
        sort_order: 3,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Shoulder Press Machine',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 4,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Smith Overhead Press',
        variant_label: 'Smith',
        variant_kind: 'support',
        sort_order: 5,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Machine',
        primary_muscle_group: 'Shoulders',
      },
    ],
  },
  {
    slug: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'strength',
    primary_muscle_group: 'Shoulders',
    primary_day: 'push',
    movement_family: 'raise',
    aliases: ['Cable Lateral Raise'],
    variants: [
      {
        source_name: 'Lateral Raise',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Cable Lateral Raise',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Shoulders',
      },
    ],
  },
  {
    slug: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    category: 'strength',
    primary_muscle_group: 'Shoulders',
    primary_day: 'push',
    movement_family: 'fly',
    aliases: ['Reverse Pec Deck'],
    variants: [
      {
        source_name: 'Rear Delt Fly',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Reverse Pec Deck',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Shoulders',
      },
    ],
  },
  {
    slug: 'upright-row',
    name: 'Upright Row',
    category: 'strength',
    primary_muscle_group: 'Shoulders',
    primary_day: 'push',
    movement_family: 'row',
    aliases: ['Barbell Upright Row', 'Dumbbell Upright Row'],
    variants: [
      {
        source_name: 'Upright Row',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Shoulders',
      },
      {
        source_name: 'Dumbbell Upright Row',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'compound',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Shoulders',
      },
    ],
  },
  {
    slug: 'curl',
    name: 'Curl',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'pull',
    movement_family: 'curl',
    aliases: ['Biceps Curl', 'Barbell Curl', 'Hammer Curl', 'Preacher Curl', 'Cable Curl'],
    variants: [
      {
        source_name: 'Biceps Curl',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Barbell Curl',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Barbell',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Hammer Curl',
        variant_label: 'Hammer Dumbbell',
        variant_kind: 'load_style',
        sort_order: 3,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Preacher Curl',
        variant_label: 'Machine',
        variant_kind: 'support',
        sort_order: 4,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Machine',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Cable Curl',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 5,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'push',
    movement_family: 'pushdown',
    aliases: ['Cable Triceps Pushdown', 'Dumbbell Triceps Pushdown'],
    variants: [
      {
        source_name: 'Triceps Pushdown',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Dumbbell Triceps Pushdown',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'push',
    movement_family: 'extension',
    aliases: ['Cable Rope Overhead Extension'],
    variants: [
      {
        source_name: 'Overhead Triceps Extension',
        variant_label: 'Dumbbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Cable Rope Overhead Extension',
        variant_label: 'Cable Rope',
        variant_kind: 'equipment',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'push',
    movement_family: 'extension',
    aliases: ['Lying Triceps Extension'],
    variants: [
      {
        source_name: 'Skull Crusher',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Barbell',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'close-grip-press',
    name: 'Close-Grip Press',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'push',
    movement_family: 'press',
    aliases: ['Close Grip Bench Press'],
    variants: [
      {
        source_name: 'Close Grip Bench Press',
        variant_label: 'Barbell',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Barbell',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'wrist-curl',
    name: 'Wrist Curl',
    category: 'strength',
    primary_muscle_group: 'Arms',
    primary_day: 'general',
    movement_family: 'curl',
    aliases: ['Reverse Wrist Curl'],
    variants: [
      {
        source_name: 'Wrist Curl',
        variant_label: 'Palms Up Dumbbell',
        variant_kind: 'position',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
      {
        source_name: 'Reverse Wrist Curl',
        variant_label: 'Palms Down Dumbbell',
        variant_kind: 'position',
        sort_order: 2,
        is_primary_variant: false,
        type: 'isolation',
        equipment: 'Dumbbell',
        primary_muscle_group: 'Arms',
      },
    ],
  },
  {
    slug: 'plank',
    name: 'Plank',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'plank',
    aliases: [],
    variants: [
      {
        source_name: 'Plank',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'side-plank',
    name: 'Side Plank',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'plank',
    aliases: [],
    variants: [
      {
        source_name: 'Side Plank',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'raise',
    aliases: [],
    variants: [
      {
        source_name: 'Hanging Leg Raise',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'crunch',
    name: 'Crunch',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'crunch',
    aliases: ['Cable Crunch'],
    variants: [
      {
        source_name: 'Cable Crunch',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'russian-twist',
    name: 'Russian Twist',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'rotation',
    aliases: [],
    variants: [
      {
        source_name: 'Russian Twist',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'stability',
    aliases: [],
    variants: [
      {
        source_name: 'Dead Bug',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'rollout',
    name: 'Rollout',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'rollout',
    aliases: ['Ab Wheel Rollout'],
    variants: [
      {
        source_name: 'Ab Wheel Rollout',
        variant_label: 'Bodyweight Wheel',
        variant_kind: 'support',
        sort_order: 1,
        is_primary_variant: true,
        type: 'compound',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'pallof-press',
    name: 'Pallof Press',
    category: 'strength',
    primary_muscle_group: 'Core',
    primary_day: 'general',
    movement_family: 'press',
    aliases: [],
    variants: [
      {
        source_name: 'Pallof Press',
        variant_label: 'Cable',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'isolation',
        equipment: 'Cable',
        primary_muscle_group: 'Core',
      },
    ],
  },
  {
    slug: 'rowing-sprint',
    name: 'Rowing Sprint',
    category: 'cardio',
    primary_muscle_group: 'Cardio',
    primary_day: 'general',
    movement_family: 'cardio',
    aliases: ['Row Sprint'],
    variants: [
      {
        source_name: 'Rowing Sprint',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'cardio',
        equipment: 'Machine',
        primary_muscle_group: 'Cardio',
      },
    ],
  },
  {
    slug: 'treadmill-run',
    name: 'Treadmill Run',
    category: 'cardio',
    primary_muscle_group: 'Cardio',
    primary_day: 'general',
    movement_family: 'cardio',
    aliases: ['Run'],
    variants: [
      {
        source_name: 'Treadmill Run',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'cardio',
        equipment: 'Machine',
        primary_muscle_group: 'Cardio',
      },
    ],
  },
  {
    slug: 'bike-sprint',
    name: 'Bike Sprint',
    category: 'cardio',
    primary_muscle_group: 'Cardio',
    primary_day: 'general',
    movement_family: 'cardio',
    aliases: ['Air Bike Sprint'],
    variants: [
      {
        source_name: 'Bike Sprint',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'cardio',
        equipment: 'Machine',
        primary_muscle_group: 'Cardio',
      },
    ],
  },
  {
    slug: 'stair-climb',
    name: 'Stair Climb',
    category: 'cardio',
    primary_muscle_group: 'Cardio',
    primary_day: 'general',
    movement_family: 'cardio',
    aliases: ['Stair Climber'],
    variants: [
      {
        source_name: 'Stair Climber',
        variant_label: 'Machine',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'cardio',
        equipment: 'Machine',
        primary_muscle_group: 'Cardio',
      },
    ],
  },
  {
    slug: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    primary_muscle_group: 'Cardio',
    primary_day: 'general',
    movement_family: 'cardio',
    aliases: ['Skipping'],
    variants: [
      {
        source_name: 'Jump Rope',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'cardio',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Cardio',
      },
    ],
  },
  {
    slug: 'dynamic-hip-mobility',
    name: 'Dynamic Hip Mobility',
    category: 'mobility',
    primary_muscle_group: 'Mobility',
    primary_day: 'general',
    movement_family: 'mobility',
    aliases: ['Hip Mobility'],
    variants: [
      {
        source_name: 'Dynamic Hip Mobility',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'mobility',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Mobility',
      },
    ],
  },
  {
    slug: 'thoracic-rotation-mobility',
    name: 'Thoracic Rotation Mobility',
    category: 'mobility',
    primary_muscle_group: 'Mobility',
    primary_day: 'general',
    movement_family: 'mobility',
    aliases: ['Thoracic Mobility'],
    variants: [
      {
        source_name: 'Thoracic Rotation Mobility',
        variant_label: 'Bodyweight',
        variant_kind: 'equipment',
        sort_order: 1,
        is_primary_variant: true,
        type: 'mobility',
        equipment: 'Bodyweight',
        primary_muscle_group: 'Mobility',
      },
    ],
  },
];

function flattenMovementCatalog(catalog = EXERCISE_MOVEMENT_CATALOG) {
  return catalog.flatMap((movement) =>
    (movement.variants || []).map((variant) => ({
      name: variant.source_name,
      type: variant.type,
      primary_muscle_group: variant.primary_muscle_group || movement.primary_muscle_group,
      equipment: variant.equipment,
    })),
  );
}

function buildVariantLookup(catalog = EXERCISE_MOVEMENT_CATALOG) {
  return Object.fromEntries(
    catalog.flatMap((movement) =>
      (movement.variants || []).map((variant) => [
        String(variant.source_name || '').trim().toLowerCase(),
        {
          movement_slug: movement.slug,
          movement_name: movement.name,
          category: movement.category,
          primary_muscle_group: movement.primary_muscle_group,
          primary_day: movement.primary_day,
          movement_family: movement.movement_family || null,
          aliases: Array.isArray(movement.aliases) ? movement.aliases : [],
          variant_label: variant.variant_label,
          variant_kind: variant.variant_kind,
          sort_order: Number(variant.sort_order || 1),
          is_primary_variant: Boolean(variant.is_primary_variant),
          type: variant.type,
          equipment: variant.equipment,
          variant_primary_muscle_group: variant.primary_muscle_group || movement.primary_muscle_group,
        },
      ]),
    ),
  );
}

module.exports = {
  EXERCISE_MOVEMENT_CATALOG,
  flattenMovementCatalog,
  buildVariantLookup,
};
